#
# Autogenerated by Thrift Compiler (0.10.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
import sys
from .ttypes import *
RESPONSE_CODE_MAP = {
    401: "UNAUTHORIZED NODE",
    0: "SUCCESS",
    -267390975: "UNDEFINED CODE",
}
