/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package gov.sequarius.dockercenter.common.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class idlConstants {

  public static final java.util.Map<Integer,String> RESPONSE_CODE_MAP = new java.util.HashMap<Integer,String>();
  static {
    RESPONSE_CODE_MAP.put(401, "UNAUTHORIZED NODE");
    RESPONSE_CODE_MAP.put(0, "SUCCESS");
    RESPONSE_CODE_MAP.put(-267390975, "UNDEFINED CODE");
  }

}
