thrift:
  server:
    name: CenterThriftServer
    port: 9047

spring:
  redis:
    host: localhost
    port: 6379

gov:
 sequarius:
  docker:
    center:
      max-history-record: 500
      max-node-count: 100

logging:
  level:
    root: info
    gov.sequarius: debug